FROM debian
MAINTAINER 谢致邦 <Yeking@Red54.com>
COPY apt /etc/apt
RUN apt-get update && apt-get install -y \
	apt-file \
	automake \
	ca-certificates \
	colordiff \
	deborphan \
	devscripts \
	dnsutils \
	dpkg-dev \
	file \
	gccxml \
	gawk \
	git \
	less \
	lib32z1 \
	libncurses5-dev \
	libssl-dev \
	libtool \
	make \
	man-db \
	net-tools \
	openssh-client \
	p7zip \
	proxychains \
	psmisc \
	python \
	quilt \
	sharutils \
	subversion \
	unzip \
	vim \
	wget \
	xz-utils \
&& apt-file update
